language: php
php:
  - 5.6
before_script:
  - npm install -g grunt-cli
  - npm install -g bower
  - npm install
  - composer install
  - mkdir -p build/logs
script:
  - phpunit --coverage-clover build/logs/clover.xml
notifications:
  email:
    - andrzej.max.marcinkowski@gmail.com
