language: php
php:
  - 5.6
before_script:
  - npm install -g grunt-cli
  - npm install -g bower
  - npm install
  - tests/install-wp-tests.sh wordpress_test root '' localhost latest
  - cp resources/.env ~
  - composer install
  - composer db
  - mkdir -p build/logs
script:
  - phpunit --coverage-clover build/logs/clover.xml
after_script:
  - php vendor/bin/coveralls
